version: '3.4'

#networks:
  #monitoring:
    #external: true

# logging section
#x-logging:
  #&loki-logging
  #driver: loki
  #options:
    #loki-url: http://host.docker.internal:3100/loki/api/v1/push

services:
  scala-web:
    build: play-scala-starter-example
    image: kjtully/scala-web:20.10
    container_name: scala-web
    labels:
      desciption: "Play for Scala Starter - Web"
    environment:
      JAVA_OPTS: "-javaagent:/opt/appdynamics/java/javaagent.jar"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "$APPDYNAMICS_AGENT_ACCOUNT_NAME"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "$APPDYNAMICS_CONTROLLER_HOST_NAME"
      APPDYNAMICS_CONTROLLER_PORT: "$APPDYNAMICS_CONTROLLER_PORT"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "$APPDYNAMICS_CONTROLLER_SSL_ENABLED"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "Play-Scala-Docker-Compose"
      APPDYNAMICS_AGENT_TIER_NAME: "play-scala-web"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "play-scala-web"
      # MacOS - uncomment the NETVIZ env vars to use local docker-compose network
      #APPDYNAMICS_NETVIZ_AGENT_HOST: "$APPDYNAMICS_NETVIZ_AGENT_HOST"
      #APPDYNAMICS_NETVIZ_AGENT_PORT: "$APPDYNAMICS_NETVIZ_AGENT_PORT"
      #APPDYNAMICS_BROWSER_EUM_APPKEY: "$APPDYNAMICS_BROWSER_EUM_APPKEY"
      #APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTP: "$APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTP"
      #APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTPS: "$APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTPS"
      #APPDYNAMICS_BROWSER_EUM_BEACON_HTTP: "$APPDYNAMICS_BROWSER_EUM_BEACON_HTTP"
      #APPDYNAMICS_BROWSER_EUM_BEACON_HTTPS: "$APPDYNAMICS_BROWSER_EUM_BEACON_HTTPS"
      # Docker Hostname to pre-populate Jaeger link in UI
      #DOCKER_HOSTNAME: "$DOCKER_HOSTNAME"
    ports:
      - "9000:9000"
    #logging: *loki-logging

  scala-api:
    build: play-scala-rest-api-example
    image: kjtully/scala-api:20.10
    container_name: scala-api
    labels:
      desciption: "Play for Scala REST API"
    environment:
      JAVA_OPTS: "-javaagent:/opt/appdynamics/java/javaagent.jar"
      APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "$APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY"
      APPDYNAMICS_AGENT_ACCOUNT_NAME: "$APPDYNAMICS_AGENT_ACCOUNT_NAME"
      APPDYNAMICS_CONTROLLER_HOST_NAME: "$APPDYNAMICS_CONTROLLER_HOST_NAME"
      APPDYNAMICS_CONTROLLER_PORT: "$APPDYNAMICS_CONTROLLER_PORT"
      APPDYNAMICS_CONTROLLER_SSL_ENABLED: "$APPDYNAMICS_CONTROLLER_SSL_ENABLED"
      APPDYNAMICS_AGENT_APPLICATION_NAME: "Play-Scala-Docker-Compose"
      APPDYNAMICS_AGENT_TIER_NAME: "play-scala-api"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME: "true"
      APPDYNAMICS_JAVA_AGENT_REUSE_NODE_NAME_PREFIX: "play-scala-api"
      # MacOS - uncomment the NETVIZ env vars to use local docker-compose network
      #APPDYNAMICS_NETVIZ_AGENT_HOST: "$APPDYNAMICS_NETVIZ_AGENT_HOST"
      #APPDYNAMICS_NETVIZ_AGENT_PORT: "$APPDYNAMICS_NETVIZ_AGENT_PORT"
      #APPDYNAMICS_BROWSER_EUM_APPKEY: "$APPDYNAMICS_BROWSER_EUM_APPKEY"
      #APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTP: "$APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTP"
      #APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTPS: "$APPDYNAMICS_BROWSER_EUM_ADRUM_EXT_URL_HTTPS"
      #APPDYNAMICS_BROWSER_EUM_BEACON_HTTP: "$APPDYNAMICS_BROWSER_EUM_BEACON_HTTP"
      #APPDYNAMICS_BROWSER_EUM_BEACON_HTTPS: "$APPDYNAMICS_BROWSER_EUM_BEACON_HTTPS"
      # Docker Hostname to pre-populate Jaeger link in UI
      #DOCKER_HOSTNAME: "$DOCKER_HOSTNAME"
    ports:
      - "9001:9001"
    #logging: *loki-logging
